___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
import numpy as np
print (np.__version__)


1.21.4


Створити вектор з 10 елементів, заповнений одиницями:

In [4]:
Z = np.ones(10)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [7]:
Z = np.full(11, range(11))
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [8]:
Z = np.full((5, 5), 0)
print(Z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [9]:
Z = np.random.randint(0, 100, (20))
nz = np.nonzero(Z)
print(Z)
print(nz)

[23 54  3 32 77 18 52 95 76 37 51 80 16 17 95 23 74 72 41 89]
(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [20]:
print(np.nanmean(Z))
print(np.median(Z))
print(np.std(Z))

52.6
55.0
20.888752954640445


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [43]:
import random
Z = np.random.randint(0, 100, (4, 2))
A = np.random.randint(0, 100, (2, 2))
C=Z.dot(A)
print(Z)
print(A)
print(C)

[[24 93]
 [17 70]
 [52 86]
 [82 94]]
[[97  0]
 [68 43]]
[[ 8652  3999]
 [ 6409  3010]
 [10892  3698]
 [14346  4042]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [44]:
Z=C.reshape((1, 8))
print(Z)
print(np.min(Z))
M=np.max(Z)
print(M)
Z[Z==M]=0
Z


[[ 8652  3999  6409  3010 10892  3698 14346  4042]]
3010
14346


array([[ 8652,  3999,  6409,  3010, 10892,  3698,     0,  4042]])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

Дано матрицю. Знайти ранг матриці:

In [8]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [6]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [10]:
np.linalg.eigh(a)

(array([-14.30540864,  -4.34740072,  23.65280936]),
 array([[ 0.15315575,  0.88160309,  0.44645191],
        [ 0.63674998, -0.43353159,  0.6376518 ],
        [-0.75570681, -0.18661821,  0.62775861]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [18]:
a = np.random.randint(0,10,50)
print(a)
counts = np.bincount(a)
print(counts)
print(np.argmax(counts))

[1 1 2 8 7 8 7 8 1 4 5 6 7 9 7 5 0 3 6 9 2 7 9 7 3 2 6 2 1 0 5 7 5 0 1 9 9
 5 9 0 6 7 8 8 5 8 7 7 5 7]
[ 4  5  4  2  1  7  4 11  6  6]
7


Виведіть лише парні числа, що діляться на 5:

In [34]:
a = np.random.randint(0,10,50)
print(a)
b=a[a%5==0]
b[b%2==0]

[3 7 8 2 5 6 7 4 3 3 9 8 1 7 4 9 6 7 6 2 8 1 2 5 0 2 7 1 4 6 3 3 3 4 5 9 9
 5 4 5 7 4 6 7 5 0 7 0 6 9]


array([0, 0, 0])

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [36]:
M1 = np.array([[2., 5.], [1., -10.]]) # Матрица (левая часть системы)
v1 = np.array([1., 3.]) # Вектор (правая часть системы)
np.linalg.solve(M1, v1)


array([ 1. , -0.2])